name: Hexo 自动部署

# 当推送时，或每天晚上11点（国际时间15点）执行
on:
  push:
  schedule: 
    - cron: '* 15 * * *' 

jobs:
  build:
    name: Hexo 自动部署
    runs-on: ubuntu-latest

    steps:
    - name: 1. 检出
      uses: actions/checkout@v2
    
    - name: 2. 构建静态文件 
      run: |
        npm install
        npm run clean
        npm run build

    - name: 3. 部署到 GitHub Page
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.ACTION }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        
        git config --global user.name "无码"
        git config --global user.email "dev@codeless.run"
        git config --global core.quotepath false
        
        npm run deploy